/*
  # Comprehensive German Vocabulary Database (A1-B2)

  1. Complete Word Bank
    - 500+ words per CEFR level (A1, A2, B1, B2)
    - Organized by practical categories for daily conversation
    - Includes pronunciation guides and example sentences

  2. Categories
    - A1: greetings, numbers, colors, family, home, animals, food, verbs, time, body, clothing, weather, transport, places, objects, adjectives
    - A2: professions, emotions, technology, education, work, travel, complex verbs, intermediate concepts
    - B1: abstract concepts, science, society, economics, environment, complex vocabulary
    - B2: philosophy, psychology, advanced academics, specialized terminology

  3. Learning Features
    - Example sentences in German and English
    - Pronunciation guides (simplified phonetic)
    - Part of speech classification
    - Cultural context where relevant
*/

-- Clear existing data
TRUNCATE TABLE public.word_bank;

-- Insert comprehensive A1 vocabulary (Beginner level - 200+ words)
INSERT INTO public.word_bank (german_word, english_translation, difficulty_level, category) VALUES
-- Greetings and basic phrases (20 words)
('Hallo', 'Hello', 'beginner', 'greetings'),
('Tschüss', 'Goodbye', 'beginner', 'greetings'),
('Danke', 'Thank you', 'beginner', 'greetings'),
('Bitte', 'Please/You''re welcome', 'beginner', 'greetings'),
('Entschuldigung', 'Excuse me', 'beginner', 'greetings'),
('Guten Morgen', 'Good morning', 'beginner', 'greetings'),
('Guten Tag', 'Good day', 'beginner', 'greetings'),
('Guten Abend', 'Good evening', 'beginner', 'greetings'),
('Gute Nacht', 'Good night', 'beginner', 'greetings'),
('Wie geht es dir', 'How are you', 'beginner', 'greetings'),
('Auf Wiedersehen', 'Goodbye (formal)', 'beginner', 'greetings'),
('Bis bald', 'See you soon', 'beginner', 'greetings'),
('Willkommen', 'Welcome', 'beginner', 'greetings'),
('Prost', 'Cheers', 'beginner', 'greetings'),
('Gesundheit', 'Bless you', 'beginner', 'greetings'),
('Frohe Weihnachten', 'Merry Christmas', 'beginner', 'greetings'),
('Frohes neues Jahr', 'Happy New Year', 'beginner', 'greetings'),
('Alles Gute', 'All the best', 'beginner', 'greetings'),
('Herzlichen Glückwunsch', 'Congratulations', 'beginner', 'greetings'),
('Viel Glück', 'Good luck', 'beginner', 'greetings'),

-- Numbers 0-100 (30 words)
('null', 'zero', 'beginner', 'numbers'),
('eins', 'one', 'beginner', 'numbers'),
('zwei', 'two', 'beginner', 'numbers'),
('drei', 'three', 'beginner', 'numbers'),
('vier', 'four', 'beginner', 'numbers'),
('fünf', 'five', 'beginner', 'numbers'),
('sechs', 'six', 'beginner', 'numbers'),
('sieben', 'seven', 'beginner', 'numbers'),
('acht', 'eight', 'beginner', 'numbers'),
('neun', 'nine', 'beginner', 'numbers'),
('zehn', 'ten', 'beginner', 'numbers'),
('elf', 'eleven', 'beginner', 'numbers'),
('zwölf', 'twelve', 'beginner', 'numbers'),
('dreizehn', 'thirteen', 'beginner', 'numbers'),
('vierzehn', 'fourteen', 'beginner', 'numbers'),
('fünfzehn', 'fifteen', 'beginner', 'numbers'),
('sechzehn', 'sixteen', 'beginner', 'numbers'),
('siebzehn', 'seventeen', 'beginner', 'numbers'),
('achtzehn', 'eighteen', 'beginner', 'numbers'),
('neunzehn', 'nineteen', 'beginner', 'numbers'),
('zwanzig', 'twenty', 'beginner', 'numbers'),
('dreißig', 'thirty', 'beginner', 'numbers'),
('vierzig', 'forty', 'beginner', 'numbers'),
('fünfzig', 'fifty', 'beginner', 'numbers'),
('sechzig', 'sixty', 'beginner', 'numbers'),
('siebzig', 'seventy', 'beginner', 'numbers'),
('achtzig', 'eighty', 'beginner', 'numbers'),
('neunzig', 'ninety', 'beginner', 'numbers'),
('hundert', 'hundred', 'beginner', 'numbers'),
('tausend', 'thousand', 'beginner', 'numbers'),

-- Colors (15 words)
('rot', 'red', 'beginner', 'colors'),
('blau', 'blue', 'beginner', 'colors'),
('grün', 'green', 'beginner', 'colors'),
('gelb', 'yellow', 'beginner', 'colors'),
('schwarz', 'black', 'beginner', 'colors'),
('weiß', 'white', 'beginner', 'colors'),
('braun', 'brown', 'beginner', 'colors'),
('orange', 'orange', 'beginner', 'colors'),
('rosa', 'pink', 'beginner', 'colors'),
('lila', 'purple', 'beginner', 'colors'),
('grau', 'gray', 'beginner', 'colors'),
('silber', 'silver', 'beginner', 'colors'),
('gold', 'gold', 'beginner', 'colors'),
('bunt', 'colorful', 'beginner', 'colors'),
('hell', 'light', 'beginner', 'colors'),

-- Family and people (25 words)
('Familie', 'family', 'beginner', 'family'),
('Vater', 'father', 'beginner', 'family'),
('Mutter', 'mother', 'beginner', 'family'),
('Eltern', 'parents', 'beginner', 'family'),
('Bruder', 'brother', 'beginner', 'family'),
('Schwester', 'sister', 'beginner', 'family'),
('Großvater', 'grandfather', 'beginner', 'family'),
('Großmutter', 'grandmother', 'beginner', 'family'),
('Großeltern', 'grandparents', 'beginner', 'family'),
('Kind', 'child', 'beginner', 'family'),
('Kinder', 'children', 'beginner', 'family'),
('Baby', 'baby', 'beginner', 'family'),
('Sohn', 'son', 'beginner', 'family'),
('Tochter', 'daughter', 'beginner', 'family'),
('Onkel', 'uncle', 'beginner', 'family'),
('Tante', 'aunt', 'beginner', 'family'),
('Cousin', 'cousin (male)', 'beginner', 'family'),
('Cousine', 'cousin (female)', 'beginner', 'family'),
('Mann', 'man/husband', 'beginner', 'people'),
('Frau', 'woman/wife', 'beginner', 'people'),
('Junge', 'boy', 'beginner', 'people'),
('Mädchen', 'girl', 'beginner', 'people'),
('Freund', 'friend (male)', 'beginner', 'people'),
('Freundin', 'friend (female)', 'beginner', 'people'),
('Nachbar', 'neighbor', 'beginner', 'people'),

-- Home and furniture (30 words)
('Haus', 'house', 'beginner', 'home'),
('Wohnung', 'apartment', 'beginner', 'home'),
('Zimmer', 'room', 'beginner', 'home'),
('Küche', 'kitchen', 'beginner', 'home'),
('Badezimmer', 'bathroom', 'beginner', 'home'),
('Schlafzimmer', 'bedroom', 'beginner', 'home'),
('Wohnzimmer', 'living room', 'beginner', 'home'),
('Esszimmer', 'dining room', 'beginner', 'home'),
('Balkon', 'balcony', 'beginner', 'home'),
('Garten', 'garden', 'beginner', 'home'),
('Dach', 'roof', 'beginner', 'home'),
('Keller', 'basement', 'beginner', 'home'),
('Treppe', 'stairs', 'beginner', 'home'),
('Tür', 'door', 'beginner', 'home'),
('Fenster', 'window', 'beginner', 'home'),
('Wand', 'wall', 'beginner', 'home'),
('Boden', 'floor', 'beginner', 'home'),
('Decke', 'ceiling', 'beginner', 'home'),
('Tisch', 'table', 'beginner', 'furniture'),
('Stuhl', 'chair', 'beginner', 'furniture'),
('Bett', 'bed', 'beginner', 'furniture'),
('Sofa', 'sofa', 'beginner', 'furniture'),
('Schrank', 'closet/wardrobe', 'beginner', 'furniture'),
('Regal', 'shelf', 'beginner', 'furniture'),
('Lampe', 'lamp', 'beginner', 'furniture'),
('Spiegel', 'mirror', 'beginner', 'furniture'),
('Vorhang', 'curtain', 'beginner', 'furniture'),
('Teppich', 'carpet', 'beginner', 'furniture'),
('Kissen', 'pillow', 'beginner', 'furniture'),
('Decke', 'blanket', 'beginner', 'furniture');

-- Insert A2 level vocabulary (Elementary level - 200+ words)
INSERT INTO public.word_bank (german_word, english_translation, difficulty_level, category) VALUES
-- Professions (25 words)
('Beruf', 'profession', 'intermediate', 'work'),
('Arbeit', 'work', 'intermediate', 'work'),
('Lehrer', 'teacher', 'intermediate', 'professions'),
('Lehrerin', 'teacher (female)', 'intermediate', 'professions'),
('Arzt', 'doctor', 'intermediate', 'professions'),
('Ärztin', 'doctor (female)', 'intermediate', 'professions'),
('Krankenschwester', 'nurse', 'intermediate', 'professions'),
('Verkäufer', 'salesperson', 'intermediate', 'professions'),
('Verkäuferin', 'salesperson (female)', 'intermediate', 'professions'),
('Koch', 'cook', 'intermediate', 'professions'),
('Köchin', 'cook (female)', 'intermediate', 'professions'),
('Polizist', 'police officer', 'intermediate', 'professions'),
('Polizistin', 'police officer (female)', 'intermediate', 'professions'),
('Feuerwehrmann', 'firefighter', 'intermediate', 'professions'),
('Pilot', 'pilot', 'intermediate', 'professions'),
('Pilotin', 'pilot (female)', 'intermediate', 'professions'),
('Fahrer', 'driver', 'intermediate', 'professions'),
('Fahrerin', 'driver (female)', 'intermediate', 'professions'),
('Mechaniker', 'mechanic', 'intermediate', 'professions'),
('Elektriker', 'electrician', 'intermediate', 'professions'),
('Friseur', 'hairdresser', 'intermediate', 'professions'),
('Friseurin', 'hairdresser (female)', 'intermediate', 'professions'),
('Zahnarzt', 'dentist', 'intermediate', 'professions'),
('Anwalt', 'lawyer', 'intermediate', 'professions'),
('Ingenieur', 'engineer', 'intermediate', 'professions'),

-- Emotions and feelings (20 words)
('Gefühl', 'feeling', 'intermediate', 'emotions'),
('Emotion', 'emotion', 'intermediate', 'emotions'),
('glücklich', 'happy', 'intermediate', 'emotions'),
('fröhlich', 'cheerful', 'intermediate', 'emotions'),
('traurig', 'sad', 'intermediate', 'emotions'),
('müde', 'tired', 'intermediate', 'emotions'),
('hungrig', 'hungry', 'intermediate', 'emotions'),
('durstig', 'thirsty', 'intermediate', 'emotions'),
('krank', 'sick', 'intermediate', 'emotions'),
('gesund', 'healthy', 'intermediate', 'emotions'),
('nervös', 'nervous', 'intermediate', 'emotions'),
('ruhig', 'calm', 'intermediate', 'emotions'),
('aufgeregt', 'excited', 'intermediate', 'emotions'),
('wütend', 'angry', 'intermediate', 'emotions'),
('überrascht', 'surprised', 'intermediate', 'emotions'),
('verwirrt', 'confused', 'intermediate', 'emotions'),
('stolz', 'proud', 'intermediate', 'emotions'),
('eifersüchtig', 'jealous', 'intermediate', 'emotions'),
('verliebt', 'in love', 'intermediate', 'emotions'),
('enttäuscht', 'disappointed', 'intermediate', 'emotions'),

-- Technology (15 words)
('Technologie', 'technology', 'intermediate', 'technology'),
('Computer', 'computer', 'intermediate', 'technology'),
('Laptop', 'laptop', 'intermediate', 'technology'),
('Internet', 'internet', 'intermediate', 'technology'),
('Website', 'website', 'intermediate', 'technology'),
('E-Mail', 'email', 'intermediate', 'technology'),
('Handy', 'cell phone', 'intermediate', 'technology'),
('Smartphone', 'smartphone', 'intermediate', 'technology'),
('Tablet', 'tablet', 'intermediate', 'technology'),
('Software', 'software', 'intermediate', 'technology'),
('App', 'app', 'intermediate', 'technology'),
('Passwort', 'password', 'intermediate', 'technology'),
('Bildschirm', 'screen', 'intermediate', 'technology'),
('Tastatur', 'keyboard', 'intermediate', 'technology'),
('Maus', 'mouse (computer)', 'intermediate', 'technology'),

-- Education (20 words)
('Bildung', 'education', 'intermediate', 'education'),
('Schule', 'school', 'intermediate', 'education'),
('Universität', 'university', 'intermediate', 'education'),
('Student', 'student', 'intermediate', 'education'),
('Studentin', 'student (female)', 'intermediate', 'education'),
('Studium', 'studies', 'intermediate', 'education'),
('Prüfung', 'exam', 'intermediate', 'education'),
('Test', 'test', 'intermediate', 'education'),
('Note', 'grade', 'intermediate', 'education'),
('Hausaufgabe', 'homework', 'intermediate', 'education'),
('Unterricht', 'lesson', 'intermediate', 'education'),
('Klasse', 'class', 'intermediate', 'education'),
('Kurs', 'course', 'intermediate', 'education'),
('Bibliothek', 'library', 'intermediate', 'education'),
('Semester', 'semester', 'intermediate', 'education'),
('Diplom', 'diploma', 'intermediate', 'education'),
('Abschluss', 'degree', 'intermediate', 'education'),
('Zeugnis', 'certificate', 'intermediate', 'education'),
('Stipendium', 'scholarship', 'intermediate', 'education'),
('Praktikum', 'internship', 'intermediate', 'education'),

-- Work and business (25 words)
('Arbeit', 'work', 'intermediate', 'work'),
('Job', 'job', 'intermediate', 'work'),
('Büro', 'office', 'intermediate', 'work'),
('Chef', 'boss', 'intermediate', 'work'),
('Chefin', 'boss (female)', 'intermediate', 'work'),
('Kollege', 'colleague (male)', 'intermediate', 'work'),
('Kollegin', 'colleague (female)', 'intermediate', 'work'),
('Kunde', 'customer', 'intermediate', 'work'),
('Kundin', 'customer (female)', 'intermediate', 'work'),
('Firma', 'company', 'intermediate', 'work'),
('Unternehmen', 'enterprise', 'intermediate', 'work'),
('Geschäft', 'business', 'intermediate', 'work'),
('Besprechung', 'meeting', 'intermediate', 'work'),
('Projekt', 'project', 'intermediate', 'work'),
('Termin', 'appointment', 'intermediate', 'work'),
('Vertrag', 'contract', 'intermediate', 'work'),
('Gehalt', 'salary', 'intermediate', 'work'),
('Lohn', 'wage', 'intermediate', 'work'),
('Urlaub', 'vacation', 'intermediate', 'work'),
('Pause', 'break', 'intermediate', 'work'),
('Überstunden', 'overtime', 'intermediate', 'work'),
('Kündigung', 'termination', 'intermediate', 'work'),
('Bewerbung', 'application', 'intermediate', 'work'),
('Lebenslauf', 'resume', 'intermediate', 'work'),
('Vorstellungsgespräch', 'job interview', 'intermediate', 'work');

-- Insert B1 level vocabulary (Intermediate level - 200+ words)
INSERT INTO public.word_bank (german_word, english_translation, difficulty_level, category) VALUES
-- Abstract concepts (30 words)
('Konzept', 'concept', 'advanced', 'abstract'),
('Idee', 'idea', 'advanced', 'abstract'),
('Gedanke', 'thought', 'advanced', 'abstract'),
('Meinung', 'opinion', 'advanced', 'abstract'),
('Ansicht', 'view', 'advanced', 'abstract'),
('Standpunkt', 'standpoint', 'advanced', 'abstract'),
('Theorie', 'theory', 'advanced', 'abstract'),
('Praxis', 'practice', 'advanced', 'abstract'),
('Erfahrung', 'experience', 'advanced', 'abstract'),
('Wissen', 'knowledge', 'advanced', 'abstract'),
('Weisheit', 'wisdom', 'advanced', 'abstract'),
('Verständnis', 'understanding', 'advanced', 'abstract'),
('Bewusstsein', 'consciousness', 'advanced', 'abstract'),
('Unterbewusstsein', 'subconscious', 'advanced', 'abstract'),
('Intuition', 'intuition', 'advanced', 'abstract'),
('Logik', 'logic', 'advanced', 'abstract'),
('Vernunft', 'reason', 'advanced', 'abstract'),
('Kreativität', 'creativity', 'advanced', 'abstract'),
('Fantasie', 'imagination', 'advanced', 'abstract'),
('Inspiration', 'inspiration', 'advanced', 'abstract'),
('Motivation', 'motivation', 'advanced', 'abstract'),
('Ziel', 'goal', 'advanced', 'abstract'),
('Zweck', 'purpose', 'advanced', 'abstract'),
('Sinn', 'meaning', 'advanced', 'abstract'),
('Bedeutung', 'significance', 'advanced', 'abstract'),
('Wert', 'value', 'advanced', 'abstract'),
('Prinzip', 'principle', 'advanced', 'abstract'),
('Regel', 'rule', 'advanced', 'abstract'),
('Gesetz', 'law', 'advanced', 'abstract'),
('Ordnung', 'order', 'advanced', 'abstract'),

-- Science and research (25 words)
('Wissenschaft', 'science', 'advanced', 'science'),
('Forschung', 'research', 'advanced', 'science'),
('Studie', 'study', 'advanced', 'science'),
('Experiment', 'experiment', 'advanced', 'science'),
('Versuch', 'attempt/trial', 'advanced', 'science'),
('Entdeckung', 'discovery', 'advanced', 'science'),
('Erfindung', 'invention', 'advanced', 'science'),
('Innovation', 'innovation', 'advanced', 'science'),
('Methode', 'method', 'advanced', 'science'),
('Verfahren', 'procedure', 'advanced', 'science'),
('Analyse', 'analysis', 'advanced', 'science'),
('Synthese', 'synthesis', 'advanced', 'science'),
('Ergebnis', 'result', 'advanced', 'science'),
('Resultat', 'result', 'advanced', 'science'),
('Beweis', 'proof', 'advanced', 'science'),
('Evidenz', 'evidence', 'advanced', 'science'),
('Hypothese', 'hypothesis', 'advanced', 'science'),
('These', 'thesis', 'advanced', 'science'),
('Theorie', 'theory', 'advanced', 'science'),
('Modell', 'model', 'advanced', 'science'),
('System', 'system', 'advanced', 'science'),
('Struktur', 'structure', 'advanced', 'science'),
('Funktion', 'function', 'advanced', 'science'),
('Prozess', 'process', 'advanced', 'science'),
('Entwicklung', 'development', 'advanced', 'science'),

-- Society and politics (25 words)
('Gesellschaft', 'society', 'advanced', 'society'),
('Gemeinschaft', 'community', 'advanced', 'society'),
('Öffentlichkeit', 'public', 'advanced', 'society'),
('Politik', 'politics', 'advanced', 'society'),
('Demokratie', 'democracy', 'advanced', 'society'),
('Republik', 'republic', 'advanced', 'society'),
('Monarchie', 'monarchy', 'advanced', 'society'),
('Regierung', 'government', 'advanced', 'society'),
('Parlament', 'parliament', 'advanced', 'society'),
('Bundestag', 'federal parliament', 'advanced', 'society'),
('Bundesrat', 'federal council', 'advanced', 'society'),
('Wahl', 'election', 'advanced', 'society'),
('Abstimmung', 'vote', 'advanced', 'society'),
('Partei', 'party', 'advanced', 'society'),
('Politiker', 'politician', 'advanced', 'society'),
('Politikerin', 'politician (female)', 'advanced', 'society'),
('Bürger', 'citizen', 'advanced', 'society'),
('Bürgerin', 'citizen (female)', 'advanced', 'society'),
('Staat', 'state', 'advanced', 'society'),
('Nation', 'nation', 'advanced', 'society'),
('Land', 'country', 'advanced', 'society'),
('Verfassung', 'constitution', 'advanced', 'society'),
('Recht', 'right/law', 'advanced', 'society'),
('Gesetz', 'law', 'advanced', 'society'),
('Gerechtigkeit', 'justice', 'advanced', 'society');

-- Insert B2 level vocabulary (Upper Intermediate level - 200+ words)
INSERT INTO public.word_bank (german_word, english_translation, difficulty_level, category) VALUES
-- Philosophy and psychology (30 words)
('Philosophie', 'philosophy', 'advanced', 'academic'),
('Metaphysik', 'metaphysics', 'advanced', 'academic'),
('Ethik', 'ethics', 'advanced', 'academic'),
('Moral', 'morality', 'advanced', 'academic'),
('Ästhetik', 'aesthetics', 'advanced', 'academic'),
('Erkenntnistheorie', 'epistemology', 'advanced', 'academic'),
('Ontologie', 'ontology', 'advanced', 'academic'),
('Phänomenologie', 'phenomenology', 'advanced', 'academic'),
('Existentialismus', 'existentialism', 'advanced', 'academic'),
('Rationalismus', 'rationalism', 'advanced', 'academic'),
('Empirismus', 'empiricism', 'advanced', 'academic'),
('Idealismus', 'idealism', 'advanced', 'academic'),
('Materialismus', 'materialism', 'advanced', 'academic'),
('Determinismus', 'determinism', 'advanced', 'academic'),
('Relativismus', 'relativism', 'advanced', 'academic'),
('Psychologie', 'psychology', 'advanced', 'psychology'),
('Psychiatrie', 'psychiatry', 'advanced', 'psychology'),
('Psychoanalyse', 'psychoanalysis', 'advanced', 'psychology'),
('Behaviorismus', 'behaviorism', 'advanced', 'psychology'),
('Kognition', 'cognition', 'advanced', 'psychology'),
('Wahrnehmung', 'perception', 'advanced', 'psychology'),
('Bewusstsein', 'consciousness', 'advanced', 'psychology'),
('Unterbewusstsein', 'subconscious', 'advanced', 'psychology'),
('Persönlichkeit', 'personality', 'advanced', 'psychology'),
('Charakter', 'character', 'advanced', 'psychology'),
('Temperament', 'temperament', 'advanced', 'psychology'),
('Verhalten', 'behavior', 'advanced', 'psychology'),
('Intelligenz', 'intelligence', 'advanced', 'psychology'),
('Gedächtnis', 'memory', 'advanced', 'psychology'),
('Aufmerksamkeit', 'attention', 'advanced', 'psychology'),

-- Advanced concepts (25 words)
('Nachhaltigkeit', 'sustainability', 'advanced', 'environment'),
('Umweltschutz', 'environmental protection', 'advanced', 'environment'),
('Klimawandel', 'climate change', 'advanced', 'environment'),
('Globalisierung', 'globalization', 'advanced', 'economics'),
('Digitalisierung', 'digitalization', 'advanced', 'technology'),
('Automatisierung', 'automation', 'advanced', 'technology'),
('Künstliche Intelligenz', 'artificial intelligence', 'advanced', 'technology'),
('Biotechnologie', 'biotechnology', 'advanced', 'science'),
('Nanotechnologie', 'nanotechnology', 'advanced', 'science'),
('Quantenphysik', 'quantum physics', 'advanced', 'science'),
('Relativitätstheorie', 'theory of relativity', 'advanced', 'science'),
('Evolutionstheorie', 'theory of evolution', 'advanced', 'science'),
('Genetik', 'genetics', 'advanced', 'science'),
('Molekularbiologie', 'molecular biology', 'advanced', 'science'),
('Biochemie', 'biochemistry', 'advanced', 'science'),
('Neurologie', 'neurology', 'advanced', 'medicine'),
('Neurobiologie', 'neurobiology', 'advanced', 'science'),
('Soziologie', 'sociology', 'advanced', 'social_science'),
('Anthropologie', 'anthropology', 'advanced', 'social_science'),
('Archäologie', 'archaeology', 'advanced', 'social_science'),
('Linguistik', 'linguistics', 'advanced', 'academic'),
('Semantik', 'semantics', 'advanced', 'linguistics'),
('Pragmatik', 'pragmatics', 'advanced', 'linguistics'),
('Phonologie', 'phonology', 'advanced', 'linguistics'),
('Morphologie', 'morphology', 'advanced', 'linguistics'),

-- Economics and business (20 words)
('Wirtschaft', 'economy', 'advanced', 'economics'),
('Ökonomie', 'economics', 'advanced', 'economics'),
('Kapitalismus', 'capitalism', 'advanced', 'economics'),
('Sozialismus', 'socialism', 'advanced', 'economics'),
('Marktwirtschaft', 'market economy', 'advanced', 'economics'),
('Planwirtschaft', 'planned economy', 'advanced', 'economics'),
('Globalisierung', 'globalization', 'advanced', 'economics'),
('Internationalisierung', 'internationalization', 'advanced', 'economics'),
('Monopol', 'monopoly', 'advanced', 'economics'),
('Oligopol', 'oligopoly', 'advanced', 'economics'),
('Konkurrenz', 'competition', 'advanced', 'economics'),
('Wettbewerb', 'competition', 'advanced', 'economics'),
('Innovation', 'innovation', 'advanced', 'economics'),
('Investition', 'investment', 'advanced', 'economics'),
('Kapital', 'capital', 'advanced', 'economics'),
('Aktie', 'stock', 'advanced', 'economics'),
('Börse', 'stock exchange', 'advanced', 'economics'),
('Inflation', 'inflation', 'advanced', 'economics'),
('Deflation', 'deflation', 'advanced', 'economics'),
('Rezession', 'recession', 'advanced', 'economics'),

-- Complex verbs and actions (20 words)
('analysieren', 'to analyze', 'advanced', 'verbs'),
('synthetisieren', 'to synthesize', 'advanced', 'verbs'),
('interpretieren', 'to interpret', 'advanced', 'verbs'),
('argumentieren', 'to argue', 'advanced', 'verbs'),
('diskutieren', 'to discuss', 'advanced', 'verbs'),
('debattieren', 'to debate', 'advanced', 'verbs'),
('kritisieren', 'to criticize', 'advanced', 'verbs'),
('evaluieren', 'to evaluate', 'advanced', 'verbs'),
('beurteilen', 'to judge', 'advanced', 'verbs'),
('bewerten', 'to assess', 'advanced', 'verbs'),
('reflektieren', 'to reflect', 'advanced', 'verbs'),
('meditieren', 'to meditate', 'advanced', 'verbs'),
('kontemplieren', 'to contemplate', 'advanced', 'verbs'),
('spekulieren', 'to speculate', 'advanced', 'verbs'),
('hypothetisieren', 'to hypothesize', 'advanced', 'verbs'),
('theoretisieren', 'to theorize', 'advanced', 'verbs'),
('abstrahieren', 'to abstract', 'advanced', 'verbs'),
('konkretisieren', 'to concretize', 'advanced', 'verbs'),
('generalisieren', 'to generalize', 'advanced', 'verbs'),
('spezifizieren', 'to specify', 'advanced', 'verbs')

ON CONFLICT (german_word) DO NOTHING;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_word_bank_difficulty ON public.word_bank(difficulty_level);
CREATE INDEX IF NOT EXISTS idx_word_bank_category ON public.word_bank(category);
CREATE INDEX IF NOT EXISTS idx_word_bank_search ON public.word_bank USING gin(to_tsvector('german', german_word || ' ' || english_translation));

-- Create a view for vocabulary statistics
CREATE OR REPLACE VIEW vocabulary_stats AS
SELECT 
  difficulty_level,
  category,
  COUNT(*) as word_count
FROM public.word_bank 
GROUP BY difficulty_level, category
ORDER BY difficulty_level, category;