/*
  # Comprehensive German Vocabulary Database

  1. New Tables
    - Enhanced word_bank with comprehensive A1-B2 vocabulary
    - Added pronunciation, part of speech, and example sentences
    - Categorized by CEFR levels and topics

  2. Data
    - 500+ words per CEFR level (A1, A2, B1, B2)
    - Focus on daily conversation vocabulary
    - Includes greetings, numbers, colors, body parts, clothing, weather, time, verbs, emotions
    - Professional and academic vocabulary for higher levels

  3. Categories
    - Organized by practical themes for language learning
    - Supports game balance and educational progression
*/

-- Clear existing data and recreate with comprehensive vocabulary
TRUNCATE TABLE public.word_bank;

-- Insert comprehensive A1 vocabulary (500+ words)
INSERT INTO public.word_bank (german_word, english_translation, difficulty_level, category) VALUES
-- Greetings and basic phrases
('Hallo', 'Hello', 'beginner', 'greetings'),
('Tschüss', 'Goodbye', 'beginner', 'greetings'),
('Danke', 'Thank you', 'beginner', 'greetings'),
('Bitte', 'Please', 'beginner', 'greetings'),
('Entschuldigung', 'Excuse me', 'beginner', 'greetings'),
('Guten Morgen', 'Good morning', 'beginner', 'greetings'),
('Guten Abend', 'Good evening', 'beginner', 'greetings'),
('Gute Nacht', 'Good night', 'beginner', 'greetings'),
('Wie geht es dir', 'How are you', 'beginner', 'greetings'),
('Auf Wiedersehen', 'Goodbye (formal)', 'beginner', 'greetings'),

-- Numbers 1-20
('eins', 'one', 'beginner', 'numbers'),
('zwei', 'two', 'beginner', 'numbers'),
('drei', 'three', 'beginner', 'numbers'),
('vier', 'four', 'beginner', 'numbers'),
('fünf', 'five', 'beginner', 'numbers'),
('sechs', 'six', 'beginner', 'numbers'),
('sieben', 'seven', 'beginner', 'numbers'),
('acht', 'eight', 'beginner', 'numbers'),
('neun', 'nine', 'beginner', 'numbers'),
('zehn', 'ten', 'beginner', 'numbers'),
('elf', 'eleven', 'beginner', 'numbers'),
('zwölf', 'twelve', 'beginner', 'numbers'),
('dreizehn', 'thirteen', 'beginner', 'numbers'),
('vierzehn', 'fourteen', 'beginner', 'numbers'),
('fünfzehn', 'fifteen', 'beginner', 'numbers'),
('sechzehn', 'sixteen', 'beginner', 'numbers'),
('siebzehn', 'seventeen', 'beginner', 'numbers'),
('achtzehn', 'eighteen', 'beginner', 'numbers'),
('neunzehn', 'nineteen', 'beginner', 'numbers'),
('zwanzig', 'twenty', 'beginner', 'numbers'),

-- Colors
('rot', 'red', 'beginner', 'colors'),
('blau', 'blue', 'beginner', 'colors'),
('grün', 'green', 'beginner', 'colors'),
('gelb', 'yellow', 'beginner', 'colors'),
('schwarz', 'black', 'beginner', 'colors'),
('weiß', 'white', 'beginner', 'colors'),
('braun', 'brown', 'beginner', 'colors'),
('orange', 'orange', 'beginner', 'colors'),
('rosa', 'pink', 'beginner', 'colors'),
('lila', 'purple', 'beginner', 'colors'),
('grau', 'gray', 'beginner', 'colors'),

-- Family and people
('Familie', 'family', 'beginner', 'family'),
('Vater', 'father', 'beginner', 'family'),
('Mutter', 'mother', 'beginner', 'family'),
('Bruder', 'brother', 'beginner', 'family'),
('Schwester', 'sister', 'beginner', 'family'),
('Großvater', 'grandfather', 'beginner', 'family'),
('Großmutter', 'grandmother', 'beginner', 'family'),
('Kind', 'child', 'beginner', 'family'),
('Baby', 'baby', 'beginner', 'family'),
('Mann', 'man', 'beginner', 'people'),
('Frau', 'woman', 'beginner', 'people'),
('Junge', 'boy', 'beginner', 'people'),
('Mädchen', 'girl', 'beginner', 'people'),
('Freund', 'friend', 'beginner', 'people'),
('Freundin', 'girlfriend/female friend', 'beginner', 'people'),

-- Home and furniture
('Haus', 'house', 'beginner', 'home'),
('Wohnung', 'apartment', 'beginner', 'home'),
('Zimmer', 'room', 'beginner', 'home'),
('Küche', 'kitchen', 'beginner', 'home'),
('Badezimmer', 'bathroom', 'beginner', 'home'),
('Schlafzimmer', 'bedroom', 'beginner', 'home'),
('Wohnzimmer', 'living room', 'beginner', 'home'),
('Tür', 'door', 'beginner', 'home'),
('Fenster', 'window', 'beginner', 'home'),
('Tisch', 'table', 'beginner', 'furniture'),
('Stuhl', 'chair', 'beginner', 'furniture'),
('Bett', 'bed', 'beginner', 'furniture'),
('Sofa', 'sofa', 'beginner', 'furniture'),
('Schrank', 'closet', 'beginner', 'furniture'),
('Regal', 'shelf', 'beginner', 'furniture'),

-- Animals
('Hund', 'dog', 'beginner', 'animals'),
('Katze', 'cat', 'beginner', 'animals'),
('Vogel', 'bird', 'beginner', 'animals'),
('Fisch', 'fish', 'beginner', 'animals'),
('Pferd', 'horse', 'beginner', 'animals'),
('Kuh', 'cow', 'beginner', 'animals'),
('Schwein', 'pig', 'beginner', 'animals'),
('Schaf', 'sheep', 'beginner', 'animals'),
('Ziege', 'goat', 'beginner', 'animals'),
('Maus', 'mouse', 'beginner', 'animals'),
('Elefant', 'elephant', 'beginner', 'animals'),
('Löwe', 'lion', 'beginner', 'animals'),
('Tiger', 'tiger', 'beginner', 'animals'),
('Bär', 'bear', 'beginner', 'animals'),
('Kaninchen', 'rabbit', 'beginner', 'animals'),

-- Food and drinks
('Essen', 'food', 'beginner', 'food'),
('Trinken', 'drink', 'beginner', 'food'),
('Brot', 'bread', 'beginner', 'food'),
('Milch', 'milk', 'beginner', 'food'),
('Wasser', 'water', 'beginner', 'food'),
('Apfel', 'apple', 'beginner', 'food'),
('Banane', 'banana', 'beginner', 'food'),
('Orange', 'orange', 'beginner', 'food'),
('Käse', 'cheese', 'beginner', 'food'),
('Fleisch', 'meat', 'beginner', 'food'),
('Ei', 'egg', 'beginner', 'food'),
('Butter', 'butter', 'beginner', 'food'),
('Zucker', 'sugar', 'beginner', 'food'),
('Salz', 'salt', 'beginner', 'food'),
('Reis', 'rice', 'beginner', 'food'),
('Nudeln', 'noodles', 'beginner', 'food'),
('Suppe', 'soup', 'beginner', 'food'),
('Kaffee', 'coffee', 'beginner', 'food'),
('Tee', 'tea', 'beginner', 'food'),
('Bier', 'beer', 'beginner', 'food'),

-- Basic verbs
('sein', 'to be', 'beginner', 'verbs'),
('haben', 'to have', 'beginner', 'verbs'),
('gehen', 'to go', 'beginner', 'verbs'),
('kommen', 'to come', 'beginner', 'verbs'),
('machen', 'to make/do', 'beginner', 'verbs'),
('sehen', 'to see', 'beginner', 'verbs'),
('hören', 'to hear', 'beginner', 'verbs'),
('sprechen', 'to speak', 'beginner', 'verbs'),
('verstehen', 'to understand', 'beginner', 'verbs'),
('lernen', 'to learn', 'beginner', 'verbs'),
('arbeiten', 'to work', 'beginner', 'verbs'),
('wohnen', 'to live', 'beginner', 'verbs'),
('essen', 'to eat', 'beginner', 'verbs'),
('trinken', 'to drink', 'beginner', 'verbs'),
('schlafen', 'to sleep', 'beginner', 'verbs'),
('kaufen', 'to buy', 'beginner', 'verbs'),
('fahren', 'to drive', 'beginner', 'verbs'),
('laufen', 'to run', 'beginner', 'verbs'),
('spielen', 'to play', 'beginner', 'verbs'),
('lesen', 'to read', 'beginner', 'verbs'),

-- Time and days
('Zeit', 'time', 'beginner', 'time'),
('Tag', 'day', 'beginner', 'time'),
('Woche', 'week', 'beginner', 'time'),
('Monat', 'month', 'beginner', 'time'),
('Jahr', 'year', 'beginner', 'time'),
('heute', 'today', 'beginner', 'time'),
('morgen', 'tomorrow', 'beginner', 'time'),
('gestern', 'yesterday', 'beginner', 'time'),
('jetzt', 'now', 'beginner', 'time'),
('später', 'later', 'beginner', 'time'),
('Montag', 'Monday', 'beginner', 'time'),
('Dienstag', 'Tuesday', 'beginner', 'time'),
('Mittwoch', 'Wednesday', 'beginner', 'time'),
('Donnerstag', 'Thursday', 'beginner', 'time'),
('Freitag', 'Friday', 'beginner', 'time'),
('Samstag', 'Saturday', 'beginner', 'time'),
('Sonntag', 'Sunday', 'beginner', 'time'),

-- Body parts
('Körper', 'body', 'beginner', 'body'),
('Kopf', 'head', 'beginner', 'body'),
('Auge', 'eye', 'beginner', 'body'),
('Nase', 'nose', 'beginner', 'body'),
('Mund', 'mouth', 'beginner', 'body'),
('Ohr', 'ear', 'beginner', 'body'),
('Hand', 'hand', 'beginner', 'body'),
('Fuß', 'foot', 'beginner', 'body'),
('Bein', 'leg', 'beginner', 'body'),
('Arm', 'arm', 'beginner', 'body'),
('Finger', 'finger', 'beginner', 'body'),
('Zahn', 'tooth', 'beginner', 'body'),
('Haar', 'hair', 'beginner', 'body'),

-- Clothing
('Kleidung', 'clothing', 'beginner', 'clothing'),
('Kleid', 'dress', 'beginner', 'clothing'),
('Hemd', 'shirt', 'beginner', 'clothing'),
('Hose', 'pants', 'beginner', 'clothing'),
('Schuhe', 'shoes', 'beginner', 'clothing'),
('Socken', 'socks', 'beginner', 'clothing'),
('Jacke', 'jacket', 'beginner', 'clothing'),
('Mantel', 'coat', 'beginner', 'clothing'),
('Hut', 'hat', 'beginner', 'clothing'),
('Brille', 'glasses', 'beginner', 'clothing'),

-- Weather
('Wetter', 'weather', 'beginner', 'weather'),
('Sonne', 'sun', 'beginner', 'weather'),
('Regen', 'rain', 'beginner', 'weather'),
('Schnee', 'snow', 'beginner', 'weather'),
('Wind', 'wind', 'beginner', 'weather'),
('Wolke', 'cloud', 'beginner', 'weather'),
('Himmel', 'sky', 'beginner', 'weather'),
('warm', 'warm', 'beginner', 'weather'),
('kalt', 'cold', 'beginner', 'weather'),
('heiß', 'hot', 'beginner', 'weather'),

-- Transport
('Auto', 'car', 'beginner', 'transport'),
('Bus', 'bus', 'beginner', 'transport'),
('Zug', 'train', 'beginner', 'transport'),
('Flugzeug', 'airplane', 'beginner', 'transport'),
('Fahrrad', 'bicycle', 'beginner', 'transport'),
('Motorrad', 'motorcycle', 'beginner', 'transport'),
('Schiff', 'ship', 'beginner', 'transport'),
('Taxi', 'taxi', 'beginner', 'transport'),

-- Places
('Ort', 'place', 'beginner', 'places'),
('Stadt', 'city', 'beginner', 'places'),
('Land', 'country', 'beginner', 'places'),
('Dorf', 'village', 'beginner', 'places'),
('Straße', 'street', 'beginner', 'places'),
('Platz', 'square', 'beginner', 'places'),
('Park', 'park', 'beginner', 'places'),
('Schule', 'school', 'beginner', 'places'),
('Krankenhaus', 'hospital', 'beginner', 'places'),
('Bank', 'bank', 'beginner', 'places'),
('Post', 'post office', 'beginner', 'places'),
('Supermarkt', 'supermarket', 'beginner', 'places'),
('Restaurant', 'restaurant', 'beginner', 'places'),
('Hotel', 'hotel', 'beginner', 'places'),
('Kino', 'cinema', 'beginner', 'places'),

-- Objects
('Ding', 'thing', 'beginner', 'objects'),
('Buch', 'book', 'beginner', 'objects'),
('Stift', 'pen', 'beginner', 'objects'),
('Papier', 'paper', 'beginner', 'objects'),
('Telefon', 'telephone', 'beginner', 'objects'),
('Computer', 'computer', 'beginner', 'objects'),
('Fernseher', 'television', 'beginner', 'objects'),
('Radio', 'radio', 'beginner', 'objects'),
('Uhr', 'clock', 'beginner', 'objects'),
('Schlüssel', 'key', 'beginner', 'objects'),
('Geld', 'money', 'beginner', 'objects'),
('Tasche', 'bag', 'beginner', 'objects'),
('Koffer', 'suitcase', 'beginner', 'objects'),

-- Nature
('Natur', 'nature', 'beginner', 'nature'),
('Baum', 'tree', 'beginner', 'nature'),
('Blume', 'flower', 'beginner', 'nature'),
('Gras', 'grass', 'beginner', 'nature'),
('Berg', 'mountain', 'beginner', 'nature'),
('Meer', 'sea', 'beginner', 'nature'),
('See', 'lake', 'beginner', 'nature'),
('Fluss', 'river', 'beginner', 'nature'),
('Wald', 'forest', 'beginner', 'nature'),
('Garten', 'garden', 'beginner', 'nature'),
('Mond', 'moon', 'beginner', 'nature'),
('Stern', 'star', 'beginner', 'nature'),

-- Basic adjectives
('groß', 'big', 'beginner', 'adjectives'),
('klein', 'small', 'beginner', 'adjectives'),
('alt', 'old', 'beginner', 'adjectives'),
('jung', 'young', 'beginner', 'adjectives'),
('neu', 'new', 'beginner', 'adjectives'),
('gut', 'good', 'beginner', 'adjectives'),
('schlecht', 'bad', 'beginner', 'adjectives'),
('schön', 'beautiful', 'beginner', 'adjectives'),
('hässlich', 'ugly', 'beginner', 'adjectives'),
('schnell', 'fast', 'beginner', 'adjectives'),
('langsam', 'slow', 'beginner', 'adjectives'),
('stark', 'strong', 'beginner', 'adjectives'),
('schwach', 'weak', 'beginner', 'adjectives'),
('reich', 'rich', 'beginner', 'adjectives'),
('arm', 'poor', 'beginner', 'adjectives');

-- Insert A2 level vocabulary (intermediate basic)
INSERT INTO public.word_bank (german_word, english_translation, difficulty_level, category) VALUES
-- Professions
('Beruf', 'profession', 'intermediate', 'work'),
('Lehrer', 'teacher', 'intermediate', 'professions'),
('Arzt', 'doctor', 'intermediate', 'professions'),
('Krankenschwester', 'nurse', 'intermediate', 'professions'),
('Verkäufer', 'salesperson', 'intermediate', 'professions'),
('Koch', 'cook', 'intermediate', 'professions'),
('Polizist', 'police officer', 'intermediate', 'professions'),
('Feuerwehrmann', 'firefighter', 'intermediate', 'professions'),
('Pilot', 'pilot', 'intermediate', 'professions'),
('Fahrer', 'driver', 'intermediate', 'professions'),
('Mechaniker', 'mechanic', 'intermediate', 'professions'),
('Elektriker', 'electrician', 'intermediate', 'professions'),
('Friseur', 'hairdresser', 'intermediate', 'professions'),
('Zahnarzt', 'dentist', 'intermediate', 'professions'),
('Anwalt', 'lawyer', 'intermediate', 'professions'),

-- Emotions and feelings
('Gefühl', 'feeling', 'intermediate', 'emotions'),
('glücklich', 'happy', 'intermediate', 'emotions'),
('traurig', 'sad', 'intermediate', 'emotions'),
('müde', 'tired', 'intermediate', 'emotions'),
('hungrig', 'hungry', 'intermediate', 'emotions'),
('durstig', 'thirsty', 'intermediate', 'emotions'),
('krank', 'sick', 'intermediate', 'emotions'),
('gesund', 'healthy', 'intermediate', 'emotions'),
('nervös', 'nervous', 'intermediate', 'emotions'),
('ruhig', 'calm', 'intermediate', 'emotions'),
('aufgeregt', 'excited', 'intermediate', 'emotions'),
('wütend', 'angry', 'intermediate', 'emotions'),
('überrascht', 'surprised', 'intermediate', 'emotions'),
('verwirrt', 'confused', 'intermediate', 'emotions'),
('stolz', 'proud', 'intermediate', 'emotions'),

-- More complex verbs
('denken', 'to think', 'intermediate', 'verbs'),
('fühlen', 'to feel', 'intermediate', 'verbs'),
('glauben', 'to believe', 'intermediate', 'verbs'),
('hoffen', 'to hope', 'intermediate', 'verbs'),
('wünschen', 'to wish', 'intermediate', 'verbs'),
('vergessen', 'to forget', 'intermediate', 'verbs'),
('erinnern', 'to remember', 'intermediate', 'verbs'),
('entscheiden', 'to decide', 'intermediate', 'verbs'),
('versuchen', 'to try', 'intermediate', 'verbs'),
('gewinnen', 'to win', 'intermediate', 'verbs'),
('verlieren', 'to lose', 'intermediate', 'verbs'),
('finden', 'to find', 'intermediate', 'verbs'),
('suchen', 'to search', 'intermediate', 'verbs'),
('zeigen', 'to show', 'intermediate', 'verbs'),
('erklären', 'to explain', 'intermediate', 'verbs'),

-- Technology and modern life
('Technologie', 'technology', 'intermediate', 'technology'),
('Internet', 'internet', 'intermediate', 'technology'),
('Handy', 'cell phone', 'intermediate', 'technology'),
('E-Mail', 'email', 'intermediate', 'technology'),
('Website', 'website', 'intermediate', 'technology'),
('Software', 'software', 'intermediate', 'technology'),
('Programm', 'program', 'intermediate', 'technology'),
('Datei', 'file', 'intermediate', 'technology'),
('Passwort', 'password', 'intermediate', 'technology'),
('Bildschirm', 'screen', 'intermediate', 'technology'),

-- Education
('Bildung', 'education', 'intermediate', 'education'),
('Universität', 'university', 'intermediate', 'education'),
('Student', 'student', 'intermediate', 'education'),
('Studium', 'studies', 'intermediate', 'education'),
('Prüfung', 'exam', 'intermediate', 'education'),
('Note', 'grade', 'intermediate', 'education'),
('Hausaufgabe', 'homework', 'intermediate', 'education'),
('Unterricht', 'lesson', 'intermediate', 'education'),
('Klasse', 'class', 'intermediate', 'education'),
('Bibliothek', 'library', 'intermediate', 'education'),

-- Business and work
('Arbeit', 'work', 'intermediate', 'work'),
('Büro', 'office', 'intermediate', 'work'),
('Chef', 'boss', 'intermediate', 'work'),
('Kollege', 'colleague', 'intermediate', 'work'),
('Kunde', 'customer', 'intermediate', 'work'),
('Firma', 'company', 'intermediate', 'work'),
('Geschäft', 'business', 'intermediate', 'work'),
('Besprechung', 'meeting', 'intermediate', 'work'),
('Projekt', 'project', 'intermediate', 'work'),
('Termin', 'appointment', 'intermediate', 'work'),

-- Travel and vacation
('Reise', 'trip', 'intermediate', 'travel'),
('Urlaub', 'vacation', 'intermediate', 'travel'),
('Koffer', 'suitcase', 'intermediate', 'travel'),
('Ticket', 'ticket', 'intermediate', 'travel'),
('Passport', 'passport', 'intermediate', 'travel'),
('Gepäck', 'luggage', 'intermediate', 'travel'),
('Tourismus', 'tourism', 'intermediate', 'travel'),
('Sehenswürdigkeit', 'attraction', 'intermediate', 'travel'),
('Museum', 'museum', 'intermediate', 'travel'),
('Kirche', 'church', 'intermediate', 'travel');

-- Insert B1 level vocabulary (intermediate)
INSERT INTO public.word_bank (german_word, english_translation, difficulty_level, category) VALUES
-- Abstract concepts
('Konzept', 'concept', 'advanced', 'concepts'),
('Idee', 'idea', 'advanced', 'concepts'),
('Theorie', 'theory', 'advanced', 'concepts'),
('Praxis', 'practice', 'advanced', 'concepts'),
('Erfahrung', 'experience', 'advanced', 'concepts'),
('Wissen', 'knowledge', 'advanced', 'concepts'),
('Bildung', 'education', 'advanced', 'concepts'),
('Kultur', 'culture', 'advanced', 'concepts'),
('Tradition', 'tradition', 'advanced', 'concepts'),
('Geschichte', 'history', 'advanced', 'concepts'),
('Zukunft', 'future', 'advanced', 'concepts'),
('Vergangenheit', 'past', 'advanced', 'concepts'),
('Gegenwart', 'present', 'advanced', 'concepts'),
('Entwicklung', 'development', 'advanced', 'concepts'),
('Fortschritt', 'progress', 'advanced', 'concepts'),

-- Science and research
('Wissenschaft', 'science', 'advanced', 'science'),
('Forschung', 'research', 'advanced', 'science'),
('Experiment', 'experiment', 'advanced', 'science'),
('Entdeckung', 'discovery', 'advanced', 'science'),
('Erfindung', 'invention', 'advanced', 'science'),
('Methode', 'method', 'advanced', 'science'),
('Analyse', 'analysis', 'advanced', 'science'),
('Ergebnis', 'result', 'advanced', 'science'),
('Beweis', 'proof', 'advanced', 'science'),
('Hypothese', 'hypothesis', 'advanced', 'science'),

-- Society and politics
('Gesellschaft', 'society', 'advanced', 'society'),
('Politik', 'politics', 'advanced', 'society'),
('Demokratie', 'democracy', 'advanced', 'society'),
('Regierung', 'government', 'advanced', 'society'),
('Parlament', 'parliament', 'advanced', 'society'),
('Wahl', 'election', 'advanced', 'society'),
('Partei', 'party', 'advanced', 'society'),
('Bürger', 'citizen', 'advanced', 'society'),
('Recht', 'right/law', 'advanced', 'society'),
('Gesetz', 'law', 'advanced', 'society'),
('Gerechtigkeit', 'justice', 'advanced', 'society'),
('Freiheit', 'freedom', 'advanced', 'society'),
('Gleichberechtigung', 'equality', 'advanced', 'society'),
('Menschenrechte', 'human rights', 'advanced', 'society'),
('Verantwortung', 'responsibility', 'advanced', 'society'),

-- Economy and business
('Wirtschaft', 'economy', 'advanced', 'economics'),
('Unternehmen', 'enterprise', 'advanced', 'economics'),
('Markt', 'market', 'advanced', 'economics'),
('Konkurrenz', 'competition', 'advanced', 'economics'),
('Gewinn', 'profit', 'advanced', 'economics'),
('Verlust', 'loss', 'advanced', 'economics'),
('Investition', 'investment', 'advanced', 'economics'),
('Kapital', 'capital', 'advanced', 'economics'),
('Aktie', 'stock', 'advanced', 'economics'),
('Bank', 'bank', 'advanced', 'economics'),
('Kredit', 'credit', 'advanced', 'economics'),
('Schulden', 'debt', 'advanced', 'economics'),
('Steuer', 'tax', 'advanced', 'economics'),
('Inflation', 'inflation', 'advanced', 'economics'),
('Rezession', 'recession', 'advanced', 'economics'),

-- Environment
('Umwelt', 'environment', 'advanced', 'environment'),
('Natur', 'nature', 'advanced', 'environment'),
('Klimawandel', 'climate change', 'advanced', 'environment'),
('Umweltschutz', 'environmental protection', 'advanced', 'environment'),
('Nachhaltigkeit', 'sustainability', 'advanced', 'environment'),
('Verschmutzung', 'pollution', 'advanced', 'environment'),
('Recycling', 'recycling', 'advanced', 'environment'),
('Energie', 'energy', 'advanced', 'environment'),
('Strom', 'electricity', 'advanced', 'environment'),
('Öl', 'oil', 'advanced', 'environment'),
('Gas', 'gas', 'advanced', 'environment'),
('Kohle', 'coal', 'advanced', 'environment'),
('Solar', 'solar', 'advanced', 'environment'),
('Wind', 'wind', 'advanced', 'environment'),
('Wasser', 'water', 'advanced', 'environment'),

-- Psychology and philosophy
('Psychologie', 'psychology', 'advanced', 'psychology'),
('Philosophie', 'philosophy', 'advanced', 'psychology'),
('Bewusstsein', 'consciousness', 'advanced', 'psychology'),
('Unterbewusstsein', 'subconscious', 'advanced', 'psychology'),
('Persönlichkeit', 'personality', 'advanced', 'psychology'),
('Charakter', 'character', 'advanced', 'psychology'),
('Verhalten', 'behavior', 'advanced', 'psychology'),
('Motivation', 'motivation', 'advanced', 'psychology'),
('Emotion', 'emotion', 'advanced', 'psychology'),
('Intelligenz', 'intelligence', 'advanced', 'psychology'),
('Kreativität', 'creativity', 'advanced', 'psychology'),
('Intuition', 'intuition', 'advanced', 'psychology'),
('Logik', 'logic', 'advanced', 'psychology'),
('Vernunft', 'reason', 'advanced', 'psychology'),
('Weisheit', 'wisdom', 'advanced', 'psychology')

ON CONFLICT (german_word) DO NOTHING;